### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by cwilczewski** [TheDemise/discord.js-musicbot-addon#2]
I'm getting this error in the console anytime I try to play/search for anything:

`{ Error: spawn UNKNOWN
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at call (C:\discord.js\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\discord.js\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at msg.channel.send.then.response (C:\discord.js\node_modules\discord.js-musicbot-addon\index.js:255:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'UNKNOWN', errno: 'UNKNOWN', syscall: 'spawn' }`

**Comment by TheDemise** [comment]
Hmmm. To be honest I don't fully know what's causing this. I _did_ get the error at one point (while I've been trying to fix this), but it was when I was running three instances of the bot by accident. Else wise, me nor the people I know that use the addon have ever gotten it aside from that time.

I've re-tried the play command on the current version, the one before the recent merge, and in my currently in development update, but it doesn't seem to give me the error and just plays the music requested (example below from the current version).  
![Screenshot_7.png](https://i.imgur.com/AYZHJQ4.png)

The other bots I know use it also worked fine and dandy. Once I finish some personal things, I will continue to update this as well as try to resolve this issue and make sure it doesn't happen again.

Sorry for the inconvenience as well.

**Comment by cwilczewski** [comment]
Thanks!

**Comment by TheDemise** [comment]
I just released an update (1.4.0) which changes the way the addon plays/gets music from youtube. While it has it's con's, it does have it's pro's. Hopefully this fixed your issue. I haven't had much time to test it but I haven't had any issues yet or been told of any.

Along with that, you'll now need a YouTube API3 key for searching/playing music. It's explained a bit in the readme, along with a helpful link. Let me know how it goes~

**Comment by cwilczewski** [comment]
Hey, thanks for the update. That error seems to have gone away, but now I'm getting another one.

events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at PassThrough.Writable.write (_stream_writable.js:288:21)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at emitThree (events.js:140:20)
    at DestroyableTransform.emit (events.js:216:7)
    at emitThree (events.js:135:13)
    at FfmpegCommand.emit (events.js:216:7)
    at emitEnd (C:\Users\cwilc\disbot\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at C:\Users\cwilc\disbot\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at C:\Users\cwilc\disbot\node_modules\async\dist\async.js:421:16

I really appreciate your help!!!

**Comment by TheDemise** [comment]
Again, odd. From what I see that's an error with the `fluent-ffmpeg` module.
I tested while using the `ffmpeg-binaries` and got the error, but while using just ffmpeg installed on my system, it worked fine. Try installing it if you haven't and see if that resolves it. Something [like this link](https://www.wikihow.com/Install-FFmpeg-on-Windows) might help you install it. That's all I can really say about this right now. Sorry about that.
