### ISSUE TITLE
Crash involving the skip command.

### ISSUE THREAD

**Issue by Rodabaugh** [TheDemise/discord.js-musicbot-addon#5]
The bot crashed when skipping. I get this to happen every time by having it play a playlist (I think if you queue a few songs yourself it will still work) and then spamming the skip command a few times. Here is the error it spits out into my terminal:

>/home/erikr/Workspace/Winston/node_modules/discord.js-musicbot-addon/index.js:488
		dispatcher.end();
		          ^
>
>TypeError: Cannot read property 'end' of undefined
    at skip (/home/erikr/Workspace/Winston/node_modules/discord.js-musicbot-addon/index.js:488:13)
    at CommandoClient.client.on.msg (/home/erikr/Workspace/Winston/node_modules/discord.js-musicbot-addon/index.js:219:13)
    at emitOne (events.js:120:20)
    at CommandoClient.emit (events.js:210:7)
    at MessageCreateHandler.handle (/home/erikr/Workspace/Winston/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/erikr/Workspace/Winston/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/erikr/Workspace/Winston/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/home/erikr/Workspace/Winston/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocket.onMessage (/home/erikr/Workspace/Winston/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:115:13)

(My bot is named Winston) For now, I've just told people to just use the clearqueue command, but I know some people will still spam that. :/ I'll see about looking into this myself during my free time. Anyways, here's my bug report.

**Comment by TheDemise** [comment]
Hmmm, I've never seen that happen (well obviously, or I would have fixed it). I tried getting me and a couple friends to spam my main bot that uses this, and we didn't get the error no matter how hard we spammed. It sounds stupid, but it's just a possibility that your bot got delayed, in a sense, some way and tried to resume/end the dispatcher when there wasn't one. I've also seen to have gotten pretty sick myself, so I'm unsure when I'll be able to add my next update along with resolving this (or at least trying) but hey, if you want to take a crack at it I won't stop you, haha.

**Comment by TheDemise** [comment]
Fixed (correct me if I'm wrong) within the 1.6 update (will be reeased later, check out the preview-build branch for it now). It was due to the skip function being async. Simply put, it was just ending the dispatcher twice, or more, which caused that.
